# Generated by Django 5.2 on 2025-05-03 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task',
            field=models.CharField(default='hello', max_length=200),
            preserve_default=False,
        ),
    ]
